## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-jenkins-exporter
  name: test-jenkins-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-jenkins-exporter
  template:
    metadata:
      labels:
        app: test-jenkins-exporter
    spec:
      containers:
      - image: bitnami/jenkins-exporter
        name: jenkins-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-jenkins-exporter
  name: test-jenkins-exporter
spec:
  ports:
  - port: 9118
    protocol: TCP
    targetPort: 9118
  selector:
    app: test-jenkins-exporter
  sessionAffinity: None
  type: ClusterIP
